-- Migration 003: Product Catalog — categories, products, price_tiers, product_images

-- ── categories ────────────────────────────────────────────────────────────────
create table categories (
  id            bigint generated by default as identity primary key,
  public_id     uuid not null default gen_random_uuid() unique,
  name          text not null unique,
  slug          text not null unique,
  description   text,
  image_url     text,
  display_order int not null default 0,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create trigger categories_set_updated_at
  before update on categories
  for each row execute function set_updated_at();

-- ── products ──────────────────────────────────────────────────────────────────
create table products (
  id                bigint generated by default as identity primary key,
  public_id         uuid not null default gen_random_uuid() unique,
  category_id       bigint not null references categories(id),
  name              text not null,
  slug              text not null unique,
  description       text,
  origin            text,
  image_url         text,
  base_price        numeric(12,2) not null check (base_price >= 0),
  unit              text not null default 'kg',
  min_order_quantity int not null default 1 check (min_order_quantity > 0),
  stock_quantity    int not null default 0 check (stock_quantity >= 0),
  status            product_status not null default 'ACTIVE',
  is_featured       boolean not null default false,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz
);

create index products_category_status_idx  on products (category_id, status);
create index products_featured_status_idx  on products (is_featured, status);
create index products_stock_idx            on products (stock_quantity);

create trigger products_set_updated_at
  before update on products
  for each row execute function set_updated_at();

-- ── price_tiers ───────────────────────────────────────────────────────────────
create table price_tiers (
  id           bigint generated by default as identity primary key,
  public_id    uuid not null default gen_random_uuid() unique,
  product_id   bigint not null references products(id) on delete cascade,
  min_quantity int not null check (min_quantity > 0),
  max_quantity int check (max_quantity is null or max_quantity >= min_quantity),
  unit_price   numeric(12,2) not null check (unit_price >= 0),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index price_tiers_product_quantity_idx on price_tiers (product_id, min_quantity);

create trigger price_tiers_set_updated_at
  before update on price_tiers
  for each row execute function set_updated_at();

-- ── product_images ────────────────────────────────────────────────────────────
create table product_images (
  id            bigint generated by default as identity primary key,
  public_id     uuid not null default gen_random_uuid() unique,
  product_id    bigint not null references products(id) on delete cascade,
  image_url     text not null,
  alt_text      text,
  display_order int not null default 0,
  created_at    timestamptz not null default now()
);

create index product_images_product_order_idx on product_images (product_id, display_order);
