-- Migration 007: Warehouses

create table warehouses (
  id            bigint generated by default as identity primary key,
  public_id     uuid not null default gen_random_uuid() unique,
  name          text not null,
  address       text not null,
  phone         text,
  opening_hours text,
  latitude      numeric(10,7) not null,
  longitude     numeric(10,7) not null,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index warehouses_active_idx on warehouses (is_active);

create trigger warehouses_set_updated_at
  before update on warehouses
  for each row execute function set_updated_at();
