-- Migration 002: Roles, Users, and Foundation Indexes

-- ── roles ─────────────────────────────────────────────────────────────────────
create table roles (
  id          bigint generated by default as identity primary key,
  public_id   uuid not null default gen_random_uuid() unique,
  code        text not null unique,
  name        text not null,
  description text,
  is_system   boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Case-insensitive unique index on code
create unique index roles_code_upper_uidx on roles (upper(code));

-- ── users ─────────────────────────────────────────────────────────────────────
create table users (
  id               bigint generated by default as identity primary key,
  public_id        uuid not null default gen_random_uuid() unique,
  role_id          bigint not null references roles(id) on delete restrict,
  full_name        text not null,
  email            text not null,
  phone            text not null,
  password_hash    text not null,
  status           user_status not null default 'PENDING_APPROVAL',
  store_name       text,
  business_address text,
  tax_code         text,
  avatar_url       text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  deleted_at       timestamptz
);

-- Soft-delete-aware unique indexes
create unique index users_email_active_uidx on users (lower(email)) where deleted_at is null;
create unique index users_phone_active_uidx on users (phone)        where deleted_at is null;
create index users_status_idx   on users (status);
create index users_role_id_idx  on users (role_id);
create index users_created_idx  on users (created_at desc);

-- ── updated_at trigger ────────────────────────────────────────────────────────
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger roles_set_updated_at
  before update on roles
  for each row execute function set_updated_at();

create trigger users_set_updated_at
  before update on users
  for each row execute function set_updated_at();

-- ── Seed: default roles ───────────────────────────────────────────────────────
insert into roles (code, name, description, is_system) values
  ('ADMIN', 'Quản trị viên',  'Toàn quyền hệ thống',               true),
  ('STAFF', 'Nhân viên',      'Xử lý đơn hàng và hỗ trợ chat',     true),
  ('USER',  'Đại lý',         'Xem sản phẩm, đặt hàng, theo dõi',  true);
