-- Migration 004: Cart and Orders

-- ── carts ─────────────────────────────────────────────────────────────────────
create table carts (
  id         bigint generated by default as identity primary key,
  public_id  uuid not null default gen_random_uuid() unique,
  user_id    bigint not null unique references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index carts_updated_at_idx on carts (updated_at desc);

create trigger carts_set_updated_at
  before update on carts
  for each row execute function set_updated_at();

-- ── cart_items ────────────────────────────────────────────────────────────────
create table cart_items (
  id            bigint generated by default as identity primary key,
  public_id     uuid not null default gen_random_uuid() unique,
  cart_id       bigint not null references carts(id) on delete cascade,
  product_id    bigint not null references products(id),
  price_tier_id bigint references price_tiers(id),
  quantity      int not null check (quantity > 0),
  selected      boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (cart_id, product_id)
);

create index cart_items_cart_updated_idx on cart_items (cart_id, updated_at desc);
create index cart_items_price_tier_idx   on cart_items (price_tier_id);

create trigger cart_items_set_updated_at
  before update on cart_items
  for each row execute function set_updated_at();

-- ── orders ────────────────────────────────────────────────────────────────────
create table orders (
  id               bigint generated by default as identity primary key,
  public_id        uuid not null default gen_random_uuid() unique,
  order_code       text not null unique,
  user_id          bigint not null references users(id),
  status           order_status not null default 'PENDING',
  payment_method   payment_method not null,
  payment_status   payment_status not null default 'UNPAID',
  receiver_name    text not null,
  receiver_phone   text not null,
  shipping_address text not null,
  note             text,
  subtotal_amount  numeric(12,2) not null default 0 check (subtotal_amount >= 0),
  shipping_fee     numeric(12,2) not null default 0 check (shipping_fee >= 0),
  discount_amount  numeric(12,2) not null default 0 check (discount_amount >= 0),
  total_amount     numeric(12,2) not null default 0 check (total_amount >= 0),
  confirmed_at     timestamptz,
  shipped_at       timestamptz,
  completed_at     timestamptz,
  cancelled_at     timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index orders_user_created_idx    on orders (user_id, created_at desc);
create index orders_status_created_idx  on orders (status, created_at desc);
create index orders_order_code_idx      on orders (order_code);

create trigger orders_set_updated_at
  before update on orders
  for each row execute function set_updated_at();

-- ── order_items ───────────────────────────────────────────────────────────────
create table order_items (
  id                     bigint generated by default as identity primary key,
  public_id              uuid not null default gen_random_uuid() unique,
  order_id               bigint not null references orders(id) on delete cascade,
  product_id             bigint not null references products(id),
  product_name_snapshot  text not null,
  product_unit_snapshot  text not null,
  unit_price             numeric(12,2) not null check (unit_price >= 0),
  quantity               int not null check (quantity > 0),
  line_total             numeric(12,2) not null check (line_total >= 0),
  created_at             timestamptz not null default now()
);

create index order_items_order_idx   on order_items (order_id);
create index order_items_product_idx on order_items (product_id);

-- ── order_status_history ──────────────────────────────────────────────────────
create table order_status_history (
  id          bigint generated by default as identity primary key,
  public_id   uuid not null default gen_random_uuid() unique,
  order_id    bigint not null references orders(id) on delete cascade,
  from_status order_status,
  to_status   order_status not null,
  changed_by  bigint references users(id) on delete set null,
  note        text,
  created_at  timestamptz not null default now()
);

create index order_status_history_order_created_idx
  on order_status_history (order_id, created_at desc);
