-- Migration 005: Notifications

create table notifications (
  id                  bigint generated by default as identity primary key,
  public_id           uuid not null default gen_random_uuid() unique,
  user_id             bigint not null references users(id) on delete cascade,
  type                notification_type not null,
  title               text not null,
  body                text not null,
  related_order_id    bigint references orders(id) on delete set null,
  related_product_id  bigint references products(id) on delete set null,
  related_chat_room_id bigint,  -- FK added in migration 006 after chat_rooms is created
  is_read             boolean not null default false,
  read_at             timestamptz,
  created_at          timestamptz not null default now()
);

create index notifications_user_read_created_idx
  on notifications (user_id, is_read, created_at desc);
create index notifications_related_order_idx
  on notifications (related_order_id);
