-- Migration 006: Messaging and Complaints

-- ── chat_rooms ────────────────────────────────────────────────────────────────
create table chat_rooms (
  id                 bigint generated by default as identity primary key,
  public_id          uuid not null default gen_random_uuid() unique,
  user_id            bigint not null references users(id),
  assigned_staff_id  bigint references users(id),
  last_message_at    timestamptz,
  is_closed          boolean not null default false,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index chat_rooms_user_created_idx
  on chat_rooms (user_id, created_at desc);
create index chat_rooms_staff_last_message_idx
  on chat_rooms (assigned_staff_id, last_message_at desc);

create trigger chat_rooms_set_updated_at
  before update on chat_rooms
  for each row execute function set_updated_at();

-- Wire the deferred FK from notifications → chat_rooms
alter table notifications
  add constraint notifications_related_chat_room_id_fkey
  foreign key (related_chat_room_id)
  references chat_rooms(id) on delete set null;

-- ── chat_messages ─────────────────────────────────────────────────────────────
create table chat_messages (
  id          bigint generated by default as identity primary key,
  public_id   uuid not null default gen_random_uuid() unique,
  room_id     bigint not null references chat_rooms(id) on delete cascade,
  sender_id   bigint references users(id),
  sender_type chat_sender_type not null,
  content     text not null,
  created_at  timestamptz not null default now()
);

create index chat_messages_room_created_idx
  on chat_messages (room_id, created_at asc);
create index chat_messages_sender_created_idx
  on chat_messages (sender_id, created_at desc);

-- ── chat_attachments ──────────────────────────────────────────────────────────
create table chat_attachments (
  id               bigint generated by default as identity primary key,
  public_id        uuid not null default gen_random_uuid() unique,
  message_id       bigint not null references chat_messages(id) on delete cascade,
  uploaded_by      bigint references users(id),
  storage_bucket   text not null default 'chat-attachments',
  storage_path     text not null,
  file_name        text not null,
  mime_type        text not null,
  file_size_bytes  bigint not null check (file_size_bytes > 0),
  created_at       timestamptz not null default now()
);

create index chat_attachments_message_created_idx
  on chat_attachments (message_id, created_at asc);
create index chat_attachments_uploaded_by_created_idx
  on chat_attachments (uploaded_by, created_at desc);

-- ── complaints ────────────────────────────────────────────────────────────────
create table complaints (
  id                 bigint generated by default as identity primary key,
  public_id          uuid not null default gen_random_uuid() unique,
  user_id            bigint not null references users(id),
  order_id           bigint references orders(id) on delete set null,
  chat_room_id       bigint references chat_rooms(id) on delete set null,
  chat_message_id    bigint references chat_messages(id) on delete set null,
  title              text not null,
  description        text not null,
  status             complaint_status not null default 'OPEN',
  assigned_staff_id  bigint references users(id) on delete set null,
  resolved_at        timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index complaints_status_created_idx
  on complaints (status, created_at desc);
create index complaints_user_created_idx
  on complaints (user_id, created_at desc);
create index complaints_assigned_staff_idx
  on complaints (assigned_staff_id);
create index complaints_chat_message_idx
  on complaints (chat_message_id);

create trigger complaints_set_updated_at
  before update on complaints
  for each row execute function set_updated_at();
