-- Migration 013: User shipping addresses

create table shipping_addresses (
  id             bigint generated by default as identity primary key,
  public_id      uuid not null default gen_random_uuid() unique,
  user_id        bigint not null references users(id) on delete cascade,
  label          text,
  receiver_name  text not null,
  receiver_phone text not null,
  address_line   text not null,
  is_default     boolean not null default false,
  deleted_at     timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index shipping_addresses_user_updated_idx
  on shipping_addresses (user_id, updated_at desc)
  where deleted_at is null;

create unique index shipping_addresses_one_default_per_user_idx
  on shipping_addresses (user_id)
  where is_default and deleted_at is null;

create trigger shipping_addresses_set_updated_at
  before update on shipping_addresses
  for each row execute function set_updated_at();
