-- Migration V020: Create payments and payment_methods tables, refactor orders table

-- 1. Create payment_methods table
create table payment_methods (
  id          bigint generated by default as identity primary key,
  public_id   uuid not null default gen_random_uuid() unique,
  code        text not null unique,
  name        text not null,
  description text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- 2. Insert default payment methods
insert into payment_methods (code, name, description, is_active) values
('COD', 'Thanh toán khi nhận hàng (COD)', 'Nhận hàng rồi mới thanh toán tiền mặt', true),
('BANK_TRANSFER', 'Chuyển khoản ngân hàng', 'Chuyển khoản qua tài khoản ngân hàng của cửa hàng', true),
('VNPAY', 'Ví điện tử VNPAY QR', 'Thanh toán trực tuyến bằng cổng VNPay (ATM, Thẻ quốc tế, QR Code)', true);

-- 3. Add payment_method_id column to orders table (nullable initially)
alter table orders add column payment_method_id bigint references payment_methods(id);

-- 4. Migrate existing data from old enum payment_method column to payment_method_id
update orders o
set payment_method_id = pm.id
from payment_methods pm
where pm.code = cast(o.payment_method as text);

-- If some orders don't have payment_method or couldn't match, set a default (e.g. COD)
update orders
set payment_method_id = (select id from payment_methods where code = 'COD')
where payment_method_id is null;

-- 5. Make payment_method_id NOT NULL
alter table orders alter column payment_method_id set not null;

-- 6. Drop the old enum column payment_method from orders table
alter table orders drop column payment_method;

-- 7. Create payments table (for payment transactions/logs)
create table payments (
  id                bigint generated by default as identity primary key,
  public_id         uuid not null default gen_random_uuid() unique,
  order_id          bigint not null references orders(id) on delete cascade,
  payment_method_id bigint not null references payment_methods(id),
  amount            numeric(12,2) not null check (amount >= 0),
  status            payment_status not null default 'UNPAID',
  transaction_code  text, -- e.g. vnp_TransactionNo from VNPay
  bank_code         text, -- e.g. vnp_BankCode
  raw_response      text, -- full callback query parameters / details as JSON
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- 8. Add triggers for set_updated_at on payment_methods and payments
create trigger payment_methods_set_updated_at
  before update on payment_methods
  for each row execute function set_updated_at();

create trigger payments_set_updated_at
  before update on payments
  for each row execute function set_updated_at();
